# Generated by Django 5.1.6 on 2025-02-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedQuiz',
        ),
    ]
