# Generated by Django 5.1.6 on 2025-02-28 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquiz',
            name='numItems',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
