# Generated by Django 5.1.6 on 2025-03-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_duration', models.DurationField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours')])),
            ],
        ),
        migrations.RemoveField(
            model_name='generatedquiz',
            name='time_duration',
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appReviewer.timelimit'),
        ),
    ]
