# Generated by Django 5.1.6 on 2025-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0002_timelimit_remove_generatedquiz_time_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelimit',
            name='time_duration',
            field=models.IntegerField(choices=[(1, '1 hour'), (2, '2 hours'), (3, '3 hours')]),
        ),
    ]
