# Generated by Django 5.1.6 on 2025-03-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0003_generatedquiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedQuiz',
        ),
    ]
