# Generated by Django 5.1.6 on 2025-03-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0003_alter_timelimit_time_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelimit',
            options={'ordering': ['time_duration']},
        ),
    ]
