# Generated by Django 5.1.6 on 2025-03-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0004_delete_generatedquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appReviewer.category')),
                ('level_of_difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appReviewer.levelofdifficulty')),
                ('questions', models.ManyToManyField(to='appReviewer.question')),
                ('scenario', models.ManyToManyField(blank=True, to='appReviewer.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answers', models.JSONField(default=dict)),
                ('num_items', models.IntegerField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_questions', models.ManyToManyField(blank=True, related_name='correct_answers', to='appReviewer.question')),
                ('generated_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='appReviewer.generatedquiz')),
                ('incorrect_questions', models.ManyToManyField(blank=True, related_name='incorrect_answers', to='appReviewer.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
