# Generated by Django 5.1.6 on 2025-03-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0004_alter_timelimit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquiz',
            name='title',
            field=models.CharField(default='testtitle', max_length=20),
        ),
    ]
