# Generated by Django 5.1.6 on 2025-03-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReviewer', '0005_generatedquiz_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedquiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='generatedquiz',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
